---
- name: Install basic packages
  yum:
      state: present
      name:
          - bash-completion
          - fedora-easy-karma
          - htop
          - screen
          - tmux
          - tree
          - vim-enhanced

- name: Install packages requires to gather Pulp facts
  yum:
      state: present
      name:
          - rpm-build
          - selinux-policy

- name: Gathering Pulp facts
  pulp_facts:
